INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Mustafa', 'Kozey', 'hhane@example.org', 'Cape Verde', 'id');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Shirley', 'Fay', 'maddison.donnelly@example.org', 'Cuba', 'temporibus');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Roxanne', 'Kovacek', 'pfannerstill.arnold@example.com', 'Latvia', 'esse');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Delpha', 'Stokes', 'aylin.bartell@example.org', 'Cyprus', 'dolor');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Kory', 'Veum', 'reichel.nicolette@example.com', 'Belize', 'molestiae');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Kenny', 'Will', 'eusebio39@example.org', 'Tonga', 'aspernatur');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Jaquan', 'Kshlerin', 'stroman.gerhard@example.com', 'Martinique', 'earum');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Mossie', 'Morar', 'kaci.padberg@example.com', 'Bangladesh', 'tenetur');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Augustus', 'Murazik', 'wiza.jody@example.org', 'French Guiana', 'laborum');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Rubye', 'Schmitt', 'sporer.prudence@example.org', 'Eritrea', 'aut');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Owen', 'Price', 'swaniawski.joelle@example.net', 'Saudi Arabia', 'dolorum');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Agnes', 'Keeling', 'mertz.rodolfo@example.net', 'Saint Pierre and Miquelon', 'error');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Joana', 'Lind', 'jkub@example.org', 'New Caledonia', 'accusamus');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Vance', 'Sawayn', 'kassulke.mallory@example.org', 'Australia', 'odit');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Jazmyne', 'Parisian', 'damaris.labadie@example.com', 'Botswana', 'cumque');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Owen', 'Bauch', 'ecremin@example.com', 'Czech Republic', 'quae');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Antonette', 'Casper', 'cgutmann@example.net', 'Netherlands Antilles', 'optio');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Kristoffer', 'Homenick', 'vrunolfsdottir@example.net', 'Korea', 'dolores');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Edgardo', 'Cassin', 'wayne56@example.net', 'Luxembourg', 'quod');
INSERT INTO CODER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, COURSE) VALUES ('Destiny', 'Murphy', 'leffler.ryley@example.net', 'Malaysia', 'omnis');